version: '3.2'

services:
  gatsby:
    build:
      context: ./gatsby-cli
    entrypoint: gatsby
    volumes:
      - .:/app
  app:
    build:
      context: ./app
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
    command: sh -c "yarn develop"
    networks:
      - gatsby-container
    ports:
      - "3000:8000"


networks:
  gatsby-container:
    external: false
