version: '3.2'

services:
  gatsby:
    build:
      context: ./gatsby-cli
    entrypoint: gatsby
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
  netlify:
    build:
      context: ./netlify-cli
    entrypoint: netlify
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
  develop:
    build:
      context: ./app
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../gatsby-app
        target: /home/workspace/
    command: sh -c "rm -rf node_modules && yarn install && yarn clean  && yarn develop -H 0.0.0.0"
    networks:
      - gatsby-container
    ports:
      - "8000:8000"


networks:
  gatsby-container:
    external: true
