version: '3.2'

services:
  develop:
    build:
      context: ./app
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../
        target: /home/workspace/
    command: sh -c "yarn clean  && yarn develop -H 0.0.0.0"
    networks:
      - gatsby-container
    ports:
      - "8000:8000"

networks:
  gatsby-container:
    external: true
